name: Docker CI Pipeline

env:
  IMAGE_TAG: ct-panel-fe:latest
  DOCKER_FILE: Dockerfile
  DOCKER_WORKDIR: /app
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  CONEKTA_GP_USER: jenkins-conekta
  CONEKTA_GP_TOKEN: ${{ secrets.NPM_TOKEN }}

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
    types: ["opened", "synchronize"]

jobs:
  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Optional cache
      # - name: Cache Docker layers
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ env.IMAGE_TAG }}
          load: true
          file: ${{ env.DOCKER_FILE }}
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
          build-args: |
            CONEKTA_GP_USER=${{ env.CONEKTA_GP_USER }}
            CONEKTA_GP_TOKEN=${{ env.CONEKTA_GP_TOKEN }}
          # Optional cache
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Optional cache
      # - name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Lint
        run: docker run ${{ env.IMAGE_TAG }} sh -c  "npm run eslint-check-errors-edited"

      - name: Test
        run: docker run -v ${{ github.workspace }}/coverage:${{ env.DOCKER_WORKDIR }}/coverage ${{ env.IMAGE_TAG }} sh -c "npm test"

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{ github.workspace }}/coverage/lcov.info:lcov
